alpha/alpha/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,PasswordField,SubmitField,HiddenField, IntegerField
from wtforms.validators import EqualTo, Length,Email,DataRequired, ValidationError
from wtforms.validators import InputRequired, DataRequired, Length, ValidationError
from wtforms.widgets import Input
from werkzeug.utils import secure_filename, escape, unescape
from markupsafe import Markup
import pdb
import sqlite3
from wtforms import FileField, StringField, TextAreaField, SubmitField, SelectField, DecimalField
from wtforms.validators import InputRequired, DataRequired, Length, ValidationError
from wtforms.widgets import Input
from flask_wtf.file import FileAllowed, FileRequired
from flask_wtf.file import FileField, FileRequired
from werkzeug.utils import secure_filename
from wtforms.validators import DataRequired , Email , Length



class ItemForm(FlaskForm):
    name = StringField("name", validators=[InputRequired("Input is required!"), DataRequired("Data is required!")])
    email = StringField('Email', validators=[DataRequired("Data is required!"), Email(message="Invalid Id , Check the Format")])
    param_model = SelectField('Choose the model type',
        choices=[ ('', ''), ('monomer_model', 'monomer_model'),
        ('multimer_model', 'multimer_model')])
    param_db= SelectField('Choose the database type',
        choices=[ ('', ''), ('reduced_dbs', 'reduced_dbs'),
        ('full_dbs', 'full_dbs')])
    inputfile = FileField(validators=[InputRequired("Input is required!")])

    submit=SubmitField(label='Submit Analysis')

alpha/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
import os



basedir = os.path.abspath(os.path.dirname(__file__))

bootstrap = Bootstrap()
db = SQLAlchemy()



def create_app():
    app = Flask(__name__)
    bootstrap = Bootstrap(app)
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///alpha.db'
    app.config["MAX_CONTENT_LENGTH"] = 16 * 1024 * 1024
    app.config['SECRET_KEY'] = 'C2HWGVoMGfNTBsrYQg8EcMrdTimkZfAb'
    app.config["uploads"] = os.path.join(basedir, "uploads")
    app.config["output"] = os.path.join(basedir, "output")
    app.config["static"] = os.path.join(basedir, "static")
    app.config["images"] = os.path.join(basedir, "static", "images")
    app.config["templates"] = os.path.join(basedir, "templates")
    db.init_app(app)
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    from .alpha import alpha as alpha_blueprint
    app.register_blueprint(alpha_blueprint)
    return app

alpha/alpha/__init__.py
from flask import Blueprint

alpha = Blueprint('alpha', __name__)

from . import route
from ..model import User

alpha/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

alpha/main/views.py
from flask import render_template, request, Blueprint
from flask import render_template, redirect, url_for, flash, request
from flask_wtf.file import FileAllowed, FileRequired
from flask import Flask, send_from_directory, render_template, request, redirect, url_for, g, flash, send_file
from wtforms.widgets import Input
from werkzeug.utils import secure_filename, escape, unescape
from markupsafe import Markup
import os
from collections import defaultdict
import shutil
from flask_bootstrap import Bootstrap
from . import main



@main.route("/")
def home():
    return render_template('main_base.html')


@main.route("/home")
def home1():
    return redirect('/')

alpha/templates/alpha_error.html
{% extends "spart_base.html" %}
{% block content %}

<style>
      .alert-error {
        padding: 8px;
        background-color: red;
        color: white;
      }
    </style>

    <div class="container">
    <h1>Flashing messages</h1>
      </div>

    {% for message in get_flashed_messages() %}
    <div class="container">
      Error: {{ message }}

      </div>
    {% endfor %}

{% endblock %}

alpha/templates/alpha_first.html
{% extends 'base.html' %}

{% block title %}Please upload your sequence file - {% endblock %}

{% block content %}
<div class="row">
  <div class="col-lg-7 offset-lg-2 my-5">
    <h3>Please fill details below to submit the analysis</h3>
    <form method="POST" enctype="multipart/form-data"  action="{{ url_for('alpha.home_page') }}">

      {{ form.hidden_tag() }}


      <br>
            {{ form.name(class="form-control", placeholder="Name") }}
            <br>

            {{ form.email(class="form-control", placeholder="Email Address") }}

            <br>

            {{ form.param_model.label}}

            {{ form.param_model(class="form-control", placeholder="param_model") }}

            <br>
            {{ form.param_db.label}}

            {{ form.param_db(class="form-control", placeholder="param_db") }}

            <br>
            {{ form.inputfile.label}}

            {{ form.inputfile(class="form-control", placeholder="inputfile") }}

            <br>
            {{ form.submit(class="btn btn-lg btn-block btn-primary") }}
            <br>

   </form>



  </div>
</div>
{% endblock %}

alpha/templates/alpha_last.html
{% extends "base.html" %}


{% block content %}


<div class="container">

  <h3> The file is uploaded sucessfully, you will receive mail once analysis is over, please note the link to download</h3>

<p class="h7 pt-2 text-dark">Copy below the link address</p>
  <a href="{{ url_for('alpha.download_page', uniquestr=uniquestr) }}">LINK address</a>


</div>

{% endblock %}

alpha/templates/base.html
<!doctype html>

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>BOKU Alphafold App</title>
    <link rel="icon" href="https://boku.ac.at/typo3conf/ext/boku_template/Resources/Public/Images/boku-logo-176.svg">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <link href="/static/css1/bootstrap-override.css" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

        <!-- Optional theme -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>



    <link rel="stylesheet" href="/static/css1/custom.css">
</head>
        <style>

            table, th, td {
            border: 1px solid black;font-family:verdana;
            border-spacing: 0 30px;
            border-collapse: collapse;
            }
            th, td {
            padding: 1px;
            text-align: center;
            }
        </style>
      <title>
          {% block title %}

          {% endblock %}
      </title>
   </head>
   <body>
     <header>
         <nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-dark bg-primary">
             <div class="container">
                 <a class="navbar-brand">
                     <img src="/static/images/logo.svg" width="80" height="80" class="d-inline-block align-top"
                         alt="BOKU">
                      BOKU ALPHAFOLD APP
                 </a>

      </div>
    </nav>
      {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
           {% for category, message in messages %}
              <div class="alert alert-{{ category }}">
                  <button type="button" class="m1-2 mb-1 close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                  </button>
                  {{ message }}
              </div>
           {% endfor %}
        {% endif %}
      {% endwith %}
      {% block content %}

      {% endblock %}
      <!-- Future Content here -->


         </body>
  </html>

alpha/templates/main_base.html
<!doctype html>

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>iTaxoTools</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">


        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">

    <link rel="stylesheet" href="/static/css1/custom.css">
</head>

<header>
  <div class="container">
   <nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-dark bg-primary">

           <a class="navbar-brand">
               <img src="static/images/logo.svg" width="80" height="60" class="d-inline-block align-top"
                   alt="">
                binf-apps


        <a class="nav-link px-lg-5" href="{{ url_for('main.home') }}">
          <span class="glyphicon glyphicon-home">
          </span> binf apps</a>

      </nav>
    </div>

</header>

<br>
<br>
<br>

<body>
  <div class="container">
<div class="row justify-content-around">
<div class="col-4">
       <div class="card" style="width: 18rem;">
        <img class="card-img-top" src="static/images/logo.svg" alt="Card image cap">
        <div class="card-body">
          <p class="card-text">Alphafold app</p>
          <a href="{{ url_for('alpha.home_page') }}" class="btn btn-primary">Launch Alphafold app</a>
        </div>
      </div>
      </div>




</body>

</html>

alpha/templates/new_item.html
{% extends 'base.html' %}

{% block title %}Please upload your sequence file - {% endblock %}

{% block content %}
<div class="row">
  <div class="col-lg-7 offset-lg-2 my-5">
    <h3>Please fill details below to submit the analysis</h3>
    <form method="POST" enctype="multipart/form-data"  action="{{ url_for('home_page') }}">

      {{ form.hidden_tag() }}


      <br>
            {{ form.name(class="form-control", placeholder="Name") }}
            <br>

            {{ form.email(class="form-control", placeholder="Email Address") }}

            <br>

            {{ form.param_model.label}}

            {{ form.param_model(class="form-control", placeholder="param_model") }}

            <br>
            {{ form.param_db.label}}

            {{ form.param_db(class="form-control", placeholder="param_db") }}

            <br>
            {{ form.inputfile.label}}

            {{ form.inputfile(class="form-control", placeholder="inputfile") }}

            <br>
            {{ form.submit(class="btn btn-lg btn-block btn-primary") }}
            <br>

   </form>



  </div>
</div>
{% endblock %}